# config/routes/attributes.yaml
controllers:
    resource:
        path: ../src/Controllers/
        namespace: App\Controllers
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute